# ================================================= ==
#说明：使用 GitHub Actions 构建 v8 引擎
#作者：t1an5t
# ================================================= ==


名称：构建 v8

上：
  推：
    分支机构: [ master ]
  #观看：
  #   类型：开始

环境：
  PATCH_FLAG：错误
  提交：0
  DEPOT_UPLOAD：错误
  SRC_UPLOAD :真
  BINARY_UPLOAD：错误

#工作流运行由一个或多个可以顺序或并行运行的作业组成
职位：
  构建：
    #作业将运行的运行器类型
    运行：Windows
    如果：github.event.repository.owner.id == github.event.sender.id 	
    
    步骤：
    -名称：结帐
      使用：动作/结帐@master
      
    #初始化ubuntu1804环境
    -名称：初始化环境
      运行：|
        sudo apt-get 更新
        sudo apt-get -y install pkg-config git subversion curl wget build-essential python xz-utils zip p7zip-full
    
    #获取 depot_tools
    -名称：depot_tools
      运行：|
        git 克隆 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo export PATH=\"\$PATH:`pwd`/depot_tools/\" >> ~/.bash_profile
    
    #获取 v8 源代码
    -名称：获取 v8
      运行：|
        来源 ~/.bash_profile
        获取 v8
        CD v8
    
    #补丁源码
    -名称：补丁 v8
      如果：env.PATCH_FLAG == 'true' && !cancelled()
      运行：|
        CD v8
        git reset --hard $COMMIT
        光盘..
        
    -名称：构建 v8
      运行：|
        来源 ~/.bash_profile
        gclient同步-f
    
    #压缩这个文件
    -名称：zip depot_tools
      如果：env.DEPOT_UPLOAD == 'true' && !cancelled()
      运行：|
        zip -q -r depot_tools.zip depot_tools
        
    # 7zip v8 源码
    -名称：7zip v8_src
      运行：|
        zip -q -r v8.zip v8
        7z v8.7z ./v8.zip -v2048m
    
    #上传 depot_tools.zip 到 cowtransfer
    -名称：上传 depot_tools
      如果：env.DEPOT_UPLOAD == 'true' && !cancelled()
      运行：|
        curl -fsSL git.io/文件传输 | 嘘
        ./transfer cow --block 2621440 -s -p 64 --no-progress depot_tools.zip 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
   
    #上传 v8.zip 到 cowtransfer
    -名称：上传 v8_src
      如果：env.SRC_UPLOAD == 'true' && !cancelled()
      运行：|
        curl -fsSL git.io/文件传输 | 嘘
        ./transfer cow --block 2621440 -s -p 64 --no-progress v8.7z.001 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        ./transfer cow --block 2621440 -s -p 64 --no-progress v8.7z.002 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
